### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision.models.segmentation.segmentation'

### ISSUE THREAD

**Issue by abhishektandon-github** [MartinPernus/MaskFaceGAN#7]
I get the following error after executing the command: `python main.py --attribute mouth_slightly_open --outdir output --image input/1815.jpg`
```
Traceback (most recent call last):
  File "/home/bellman/Documents/face/MaskFaceGAN/main.py", line 7, in <module>
    from trainer import Trainer
  File "/home/bellman/Documents/face/MaskFaceGAN/trainer.py", line 7, in <module>
    from model_module import batch_mse_loss
  File "/home/bellman/Documents/face/MaskFaceGAN/model_module.py", line 6, in <module>
    from models import BranchedTiny, FaceParser, Generator
  File "/home/bellman/Documents/face/MaskFaceGAN/models/__init__.py", line 2, in <module>
    from .face_parser import FaceParser
  File "/home/bellman/Documents/face/MaskFaceGAN/models/face_parser/__init__.py", line 1, in <module>
    from .face_parser import FaceParser
  File "/home/bellman/Documents/face/MaskFaceGAN/models/face_parser/face_parser.py", line 7, in <module>
    from torchvision.models.segmentation.segmentation import deeplabv3_resnet50
ModuleNotFoundError: No module named 'torchvision.models.segmentation.segmentation'
```
I checked the directory: `anaconda3/envs/mfg/lib/python3.10/site-packages/torchvision/models/segmentation` and actually didn't find any `segmentation.py` file.

![image](https://user-images.githubusercontent.com/35254972/218267472-8434cf15-268c-4a63-9b3f-8af301680a77.png)

`conda list` gives:

![Screenshot from 2023-02-11 21-10-47](https://user-images.githubusercontent.com/35254972/218267295-13ec0d68-8d57-465f-9b59-efee44b19aa4.png)

**Comment by abhishektandon-github** [comment]
Also, I am using the converted weights file from: [Hugging Face: stylegan2-ffhq-config-f.pt](https://huggingface.co/akhaliq/jojogan-stylegan2-ffhq-config-f/blob/main/stylegan2-ffhq-config-f.pt)

**Comment by abhishektandon-github** [comment]
tried running on google colab as well, I get the same error.

![image](https://user-images.githubusercontent.com/35254972/218275142-a614214c-5a79-4ff2-bbf7-c8f9141f8273.png)

**Comment by abhishektandon-github** [comment]
turns out a few modules are depreciated in newer versions of torchvision, please specify the versions in the `requirements.txt` file. 

```
/usr/local/lib/python3.9/site-packages/torchvision/models/segmentation/segmentation.py:7: UserWarning: The 'torchvision.models.segmentation.segmentation' module is deprecated since 0.12 and will be removed in 0.14. Please use the 'torchvision.models.segmentation' directly instead.
  warnings.warn(
/usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.9/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to /root/.cache/torch/hub/checkpoints/resnet50-0676ba61.pth
100% 97.8M/97.8M [00:04<00:00, 23.7MB/s]
Traceback (most recent call last):
  File "/content/MaskFaceGAN/main.py", line 39, in <module>
    models = ModelsModule(attribute_subset=cfg.attributes, update_shape=cfg.models.update_shape,
  File "/content/MaskFaceGAN/model_module.py", line 24, in __init__
    self.face_parser = FaceParser(blend_option=blend_option)
  File "/content/MaskFaceGAN/models/face_parser/face_parser.py", line 43, in __init__
    self.load()
  File "/content/MaskFaceGAN/models/face_parser/face_parser.py", line 49, in load
    ckpt = torch.load(os.path.join(thisdir, 'state.pt'), map_location='cpu')
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/content/MaskFaceGAN/models/face_parser/state.pt'
```

**Comment by MartinPernus** [comment]
Correct, fixed the face_parser.py and added versions to the requirements.txt to fix the error.
